blog/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blog , name='all_blog'),
    path('<int:blog_id>/', views.details , name='details'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blogs(models.Model):
    blog_title = models.CharField(max_length=200)
    blog_date = models.DateField(auto_now=False) 
    blog_description = models.TextField()



    def __str__(self):
        return self.blog_title

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    discription = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)


    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blogs

def all_blog(request):
    blogs = Blogs.objects.order_by('-blog_date')

    return render(request, 'blog/all_blog.html', {'blogs':blogs})


def details(request, blog_id):
    blog = get_object_or_404(Blogs, pk=blog_id)
    return render(request, 'blog/details.html', {'blog':blog})

portfolio/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Project

def home(request):
    projects = Project.objects.all()

    return render(request, 'portfolio/home.html', {'projects':projects})

blog/templates/blog/all_blog.html
{% extends 'portfolio/base.html' %}
{% load static %}

{% block data %}
    <h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>
    <h3 class="text-center mb-5">Abdullah has written {{blogs.count}} Blog{{ blogs.count|pluralize }}</h3>

    {% for blog in blogs %}
        <div class="row justify-content-center mb-3">
            <div class="col-md-10">
                <a href="{% url 'blog:details' blog.id %}">
                    <h2>{{ blog.blog_title }}</h2>
                </a>
                <h5 class="text-muted">{{ blog.blog_date|date:'M d, Y'|upper }}</h5>
                <h4>{{ blog.blog_description|striptags|truncatechars:100 }}</h4>
            </div>
        </div>

    {% endfor %}
{% endblock %}

blog/templates/blog/details.html
{% extends 'portfolio/base.html' %}
{% load static %}

{% block data %}
    <div class="container border border-white">
    <h1 class="text-center mt-5" id="blogdetailtitle">
        {{ blog.blog_title }}
    </h1>

    <h5 class="text-center text-muted mb-5">
        {{ blog.blog_date|date:'F jS, Y'}}
    </h5>
    <p class="text-justify">
        {{ blog.blog_description|safe }}
    </p>
    </div>
{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'portfolio/custom.css'%}">
    <link href="https://fonts.googleapis.com/css?family=Tangerine" rel="stylesheet">
    
    <link rel="icon" type="image/jpeg" href="{% static 'Portfolio/AbdullahNaveed.jpeg' %}">
    <title>Abdullah Naveed</title>
</head>

<body>

  <nav id="topNav" class="navbar sticky-top navbar-expand-md navbar-light" style="background-color: #e3f2fd;">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'portfolio/AbdullahNaveed.jpeg' %}" width="30" height="30" class="d-inline-block aline-top" alt="Abdullah's Logo">
        <span>Abdullah Naveed</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% static 'portfolio/CV.pdf'%}">Resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/abdullah5naveed/" target="_blank">linkedIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://twitter.com/abdullah5naveed" target="_blank">Twitter</a>
          </li>
          <li class="nav-item">
            <a roll="button=" href="{% url 'blog:all_blog' %}" class="btn btn-primary">Blogs</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>


  <div class="container">
    {% block data %} {% endblock %}   
  </div>

<div class="row justify-content-center">
  <p class="text-center col-mt-3">copyright @AbdullahNaveed</p>
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% load static %}

{% block data %}
    <div class="row justify-content-center my-3">
        <div class="container col-5">
            <img class="img-fluid rounded-circle"src="{% static 'portfolio/AbdullahFiraas.jpg' %}">
        </div>
    </div>

    <div class="row justify-content-center mb-3">
        <div class="col-md-9 text-center">
            <h1 id="hometext" class="font-weight-bold">Abdullah Naveed is Commander In-Chief</h1>
            <h1 id="hometext" class="font-weight-bold">Python Web Developer (Django)</h1>
            <h1 id="hometext" class="font-weight-bold">Lahore,Pakistan</h1>
        </div>
    </div>

    <h1 class="mt-5">Portfolio</h1>
    <hr>

    <div class="row">
        
        {% for project in projects %}
            <div class="col-lg-4 col-md-6 border border-light rounded">
                {% if project.url %}
                       <a href="{{ project.url }}" target="_blank">
                           <img class="img-thumbnail  mb-2 rounded" src="{{ project.image.url }}">
                       </a>
                   {% else %}
                       <img class="img-thumbnail mb-2 rounded" src="{{ project.image.url }}">
                   {% endif %}
                   <h3>{{ project.title }}</h3>
                   <p>{{ project.discription }}</p>
           </div>
        {% endfor %}
    </div>
{% endblock %}